version: '3'
services:
  postgresdb: #hostname
    image: postgres:15.2
    container_name: 'postgres'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=unit-testing-training-01-05-2023

  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4:7.0
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"